from __future__ import annotations
from typing import Protocol

from rangectl.types import ExecResult, VMSpec


class Backend(Protocol):

    def create_vm(self, spec: VMSpec) -> str: ...

    def start(self, vm_id: str) -> None: ...

    def stop(self, vm_id: str) -> None: ...

    def destroy(self, vm_id: str) -> None: ...

    def snapshot(self, vm_id: str, name: str) -> str: ...

    def restore(self, vm_id: str, snapshot_id: str) -> None: ...

    def exec(self, vm_id: str, cmd: str) -> ExecResult: ...

    def upload(self, vm_id: str, src: str, dst: str) -> None: ...

    def create_bridge(self, name: str) -> str: ...

    def delete_bridge(self, name: str) -> None: ...

    def attach_interface(self, vm_id: str, bridge: str, mac: str) -> None: ...

    def create_overlay(self, base_image: str, overlay_path: str) -> str: ...

    def host_resources(self) -> HostResources: ...


class HostResources:
    total_vcpu: int
    total_memory_mb: int
    total_disk_mb: int
    available_vcpu: int
    available_memory_mb: int
    available_disk_mb: int
